paging = true
pager_command = ""
english_only = false
theme = "temp"
http_proxy = ""
clear_screen = false
freq_alert = false

[logging]
  enable = true
  path = ""
  level = "warn"
  stderr = false
  redirect_to_stream = false
